### Write a function so that the columns of the output matrix are powers of the input vector.
#### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
#### HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [8]:
import numpy as np
np.set_printoptions(suppress=True)

# Accept the input vector
try:
    in_vector = np.fromstring(input('Please enter the input vector(values separated by spaces '),dtype=int,sep=' ')
    in_dim = int(input("\nPlease enter the column dimension you would like the matrix to have "))
    flag = input('\nPlease enter YES if you need matrix power in increaing order otherwise NO ')
except Exception as e:
    print(e)
    
bflag = 99

while not((bflag == 1) or (bflag == 0)):
    if flag == 'YES':
        bflag = 1
    elif flag == 'NO':
        bflag = 0
    else:
        flag = input('\nPlease enter YES or NO only ')
    
# Initialize VandermondeMatrix matrix

X = np.ones([in_vector.shape[0],in_dim])

# perform operation on input  vector and replace the column 
for i in range(in_dim):
    X[:,i]= in_vector ** i

X = X

if bflag == 1:
    print('\nThe Vandermonde Matrix for input ',in_vector,'is ','\n', X)
else:
    print('\nThe Vandermonde Matrix for input ',in_vector,'is ','\n', np.flip(X,axis=1))

Please enter the input vector(values separated by spaces 2 3 4 5 6

Please enter the column dimension you would like the matrix to have 6

Please enter YES if you need matrix power in increaing order otherwise NO YES

The Vandermonde Matrix for input  [2 3 4 5 6] is  
 [[   1.    2.    4.    8.   16.   32.]
 [   1.    3.    9.   27.   81.  243.]
 [   1.    4.   16.   64.  256. 1024.]
 [   1.    5.   25.  125.  625. 3125.]
 [   1.    6.   36.  216. 1296. 7776.]]



### Problem Statement 2:
### Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
### The moving average sequence has n-k+1 elements as shown below.
### The moving averages with k=4 of a ten-value sequence (n=10) is shown below
#### i 1 2 3 4 5 6 7 8 9 10
#### ===== == == == == == == == == == ==
#### Input 10 20 30 40 50 60 70 80 90 100 
#### y1 25 = (10+20+30+40)/4
#### y2 35 = (20+30+40+50)/4
#### y3 45 = (30+40+50+60)/4
#### y4 55 = (40+50+60+70)/4
#### y5 65 = (50+60+70+80)/4
#### y6 75 = (60+70+80+90)/4
#### y7 85 = (70+80+90+100)/4

### Thus, the moving average sequence has n-k+1=10-4+1=7 values

In [1]:
import numpy as np

# Accept the input ARRAY

try:
    in_array = np.fromstring(input('Please enter the input array(values separated by spaces '),dtype=int,sep=' ')
    win_size = int(input("Please enter the window size "))
except Exception as e:
    print(e)

len_seq = len(in_array)-win_size +1

for i in range(len_seq):
    mov_ave = 0
    for j in range(i,i+win_size):
        mov_ave += in_array[j]
    mov_ave = mov_ave/win_size
        
    print('\nMoving average ',i+1,'is',mov_ave)


Please enter the input array(values separated by spaces 10 20 30 40 50 60 70 80 90 100
Please enter the window size 4

Moving average  1 is 25.0

Moving average  2 is 35.0

Moving average  3 is 45.0

Moving average  4 is 55.0

Moving average  5 is 65.0

Moving average  6 is 75.0

Moving average  7 is 85.0
